apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: microservices
data:
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_USER: "user"
  KONG_DATABASE: "postgres"
  KONG_PG_HOST: "kong-database"
  KONG_PG_USER: "kong"
