apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - catalog-deployment.yaml
  - orders-deployment.yaml
  - promotions-deployment.yaml
  - payment-deployment.yaml
  - rabbitmq-deployment.yaml
  - kong-deployment.yaml
  - monitoring-deployment.yaml

commonLabels:
  app: microservices
  managed-by: kustomize
