apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices
type: Opaque
stringData:
  RABBITMQ_PASS: "password"
  KONG_PG_PASSWORD: "kong"
  KONG_ADMIN_TOKEN: "kong-admin-token-secret"
