apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
  - name: catalog
    count: 2
  - name: orders
    count: 2
  - name: promotions
    count: 2
  - name: payment
    count: 2
  - name: rabbitmq
    count: 1
  - name: kong
    count: 1

images:
  - name: docker.io/DOCKERHUB_USERNAME/catalog
    newTag: staging
  - name: docker.io/DOCKERHUB_USERNAME/orders
    newTag: staging
  - name: docker.io/DOCKERHUB_USERNAME/promotions
    newTag: staging
  - name: docker.io/DOCKERHUB_USERNAME/payment
    newTag: staging
